fix: use error.sh
Signed-off-by: Kevin O'Donnell <kevin@blockchaintp.com>

diff --git a/bash/check-system b/bash/check-system
--- a/bash/check-system
+++ b/bash/check-system
@@ -5,6 +5,7 @@ source "$(dirname "${BASH_SOURCE[0]}")/includer.sh"
 @include options
 @include log
 @include commands
+@include error
 
 options::standard
 options::set_description "Checks either the local system or a list of ssh \
@@ -33,20 +34,20 @@ if [ "$USE_SSH" != "true" ]; then
 
   log::debug "${_cmd_prefix[*]} ${vendor_cmd[*]}"
   vendor=$("${_cmd_prefix[@]}" "${vendor_cmd[@]}") ||
-    error_exit "Failed to execute bios-vendor command"
+    error::exit "Failed to execute bios-vendor command"
   log::debug "${_cmd_prefix[*]} ${version_cmd[*]}"
   version=$("${_cmd_prefix[@]}" "${version_cmd[@]}") ||
-    error_exit "Failed to execute bios-version command"
+    error::exit "Failed to execute bios-version command"
   log::debug "${_cmd_prefix[*]} ${release_cmd[*]}"
   release=$("${_cmd_prefix[@]}" "${release_cmd[@]}") ||
-    error_exit "Failed to execute bios-release-date command"
+    error::exit "Failed to execute bios-release-date command"
   log::debug "${_cmd_prefix[*]} ${lsmod_cmd[*]}"
   mod_list=$("${_cmd_prefix[@]}" "${lsmod_cmd[@]}") ||
-    error_exit "Failed to execute lsmod command"
+    error::exit "Failed to execute lsmod command"
 
   if echo "$mod_list" | grep isgx; then
     log::debug "${driver_cmd[*]}"
-    driver=$("${driver_cmd[@]}") || error_exit "Failed to execute driver command"
+    driver=$("${driver_cmd[@]}") || error::exit "Failed to execute driver command"
   else
     log::warn "No ISGX driver loaded on ${host}"
     driver="(none)"
@@ -65,21 +66,21 @@ else
 
     log::debug "${_cmd_prefix[*]} ${vendor_cmd[*]} ${_cmd_postfix[*]}"
     vendor=$("${_cmd_prefix[@]}" "${vendor_cmd[@]}" "${_cmd_postfix[@]}") ||
-      error_exit "Failed to execute bios-vendor command"
+      error::exit "Failed to execute bios-vendor command"
     log::debug "${_cmd_prefix[*]} ${version_cmd[*]} ${_cmd_postfix[*]}"
     version=$("${_cmd_prefix[@]}" "${version_cmd[@]}" "${_cmd_postfix[@]}") ||
-      error_exit "Failed to execute bios-version command"
+      error::exit "Failed to execute bios-version command"
     log::debug "${_cmd_prefix[*]} ${release_cmd[*]} ${_cmd_postfix[*]}"
     release=$("${_cmd_prefix[@]}" "${release_cmd[@]}" "${_cmd_postfix[@]}") ||
-      error_exit "Failed to execute bios-release-date command"
+      error::exit "Failed to execute bios-release-date command"
     log::debug "${_cmd_prefix[*]} ${lsmod_cmd[*]} ${_cmd_postfix[*]}"
     mod_list=$("${_cmd_prefix[@]}" "${lsmod_cmd[@]}" "${_cmd_postfix[@]}") ||
-      error_exit "Failed to execute lsmod command"
+      error::exit "Failed to execute lsmod command"
 
     if echo "$mod_list" | grep -q isgx; then
       log::debug "${_cmd_prefix[*]} ${driver_cmd[*]} ${_cmd_postfix[*]}"
       driver=$("${_cmd_prefix[@]}" "${driver_cmd[@]}" "${_cmd_postfix[@]}") ||
-        error_exit "Failed to execute driver command"
+        error::exit "Failed to execute driver command"
     else
       log::warn "No ISGX driver loaded on ${host}"
       driver="(none)"
diff --git a/bash/clean-branches b/bash/clean-branches
--- a/bash/clean-branches
+++ b/bash/clean-branches
@@ -6,6 +6,7 @@ source "$(dirname "${BASH_SOURCE[0]}")/includer.sh"
 @include log
 @include git
 @include exec
+@include error
 
 options::standard
 options::set_description "Cleans the target directory of branches which have \
@@ -17,10 +18,10 @@ options::parse "$@"
 TARGET_DIR="${TARGET_DIR:-$(pwd)}"
 
 if [ ! -d "$TARGET_DIR/.git" ]; then
-  error_exit "$TARGET_DIR is not the root of a git repository"
+  error::exit "$TARGET_DIR is not the root of a git repository"
 fi
 
-cd "$TARGET_DIR" || error_exit "Failed to cd to $TARGET_DIR, check permissions"
+cd "$TARGET_DIR" || error::exit "Failed to cd to $TARGET_DIR, check permissions"
 
 log::info "Fetching for repository $TARGET_DIR"
 exec::capture git::cmd fetch -p
diff --git a/bash/on-change b/bash/on-change
--- a/bash/on-change
+++ b/bash/on-change
@@ -4,6 +4,7 @@ source "$(dirname "${BASH_SOURCE[0]}")/includer.sh"
 
 @include options
 @include log
+@include error
 
 options::standard
 options::description "A makeshift minimal CI system. It watches a directory for\
@@ -24,7 +25,7 @@ WorkingDir=${WorkingDir:-$WatchDir}
 function wait_for_change() {
   local wait_time
   wait_time="${1:-3}"
-  cd "$WatchDir" >/dev/null || error_exit "$WatchDir not found"
+  cd "$WatchDir" >/dev/null || error::exit "$WatchDir not found"
   local start_version
   start_version=$(find "$WatchDir" -ls 2>/dev/null | sort | cksum)
   local current_version
@@ -37,16 +38,16 @@ function wait_for_change() {
       current_version=$(find "$WatchDir" -ls 2>/dev/null | sort | cksum)
     fi
   done
-  cd - >/dev/null || error_exit "Failed to return to original directory"
+  cd - >/dev/null || error::exit "Failed to return to original directory"
 }
 
 function run_command() {
   log::info "Working directory $WorkingDir"
-  cd "$WorkingDir" >/dev/null || error_exit "$WorkingDir not found"
+  cd "$WorkingDir" >/dev/null || error::exit "$WorkingDir not found"
   log::info "Executing command: $*"
   "$@"
   log::info "EXIT: $?"
-  cd - >/dev/null || error_exit "Failed to return to original directory"
+  cd - >/dev/null || error::exit "Failed to return to original directory"
 }
 
 function main() {
